[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://seu-backend.onrender.com"
  VITE_SUPABASE_URL = "https://xxxx.supabase.co"
  VITE_SUPABASE_ANON_KEY = "xxxxxx"

[[redirects]]
  from = "/api/*"
  to = "https://seu-backend.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
