[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://gengastos.onrender.com"
  VITE_SUPABASE_URL = "https://wgfpxpgwwwrouizgpgfi.supabase.co"
  # VITE_SUPABASE_ANON_KEY será configurada via Dashboard do Netlify

[[redirects]]
  from = "/api/*"
  to = "https://gengastos.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
